# Generated by Django 5.2.2 on 2025-06-14 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('scheduled_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'get_latest_by': 'title',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveIntegerField(default=0)),
                ('display_name', models.CharField(default='', max_length=255)),
                ('current_score', models.PositiveIntegerField(default=0)),
                ('is_connected', models.BooleanField(default=False)),
                ('auth_id', models.CharField(default='', max_length=10)),
            ],
            options={
                'get_latest_by': 'auth_id',
            },
        ),
        migrations.CreateModel(
            name='ExamRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=255)),
                ('players', models.CharField(default=',,,', max_length=255)),
                ('total_score', models.CharField(default='0,0,0,0', max_length=255)),
                ('played_at', models.DateTimeField(auto_now_add=True)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.exam')),
            ],
            options={
                'get_latest_by': ['exam', 'played_at'],
            },
        ),
    ]
