# Generated by Django 5.2.2 on 2025-06-14 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCNVControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_question', models.BooleanField(default=False)),
                ('show_result', models.BooleanField(default=False)),
                ('disabled_players', models.CharField(default='0,0,0,0', max_length=10)),
                ('players_answer_cnv', models.CharField(default='0,0,0,0', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='KDControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_question', models.BooleanField(default=False)),
                ('current_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kd_current_player', to='olympia.player')),
                ('player_steal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kd_player_steal', to='olympia.player')),
            ],
        ),
        migrations.CreateModel(
            name='KDQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveBigIntegerField(default=0)),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
                ('question_data_type', models.CharField(choices=[('I', 'Image'), ('A', 'Audio'), ('V', 'Video'), ('T', 'Text')], default='Text', max_length=10)),
                ('question_value', models.PositiveIntegerField(default=10)),
                ('resources', models.JSONField(default={'Audio': {}, 'Image': {}, 'Video': {}})),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.exam')),
                ('target_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kd_target_player', to='olympia.player')),
            ],
            options={
                'get_latest_by': ['exam', 'no'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='KDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.PositiveIntegerField(default=0)),
                ('question_data_type', models.CharField(default='Text', max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_value', models.PositiveIntegerField(default=10)),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('question_resources', models.JSONField(default={'Audio': {}, 'Image': {}, 'Video': {}})),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kd_player_record', to='olympia.player')),
                ('player_steal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kd_steal_record', to='olympia.player')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.kdquestion')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.examrecord')),
            ],
            options={
                'get_latest_by': ['exam', 'record', 'question', 'question_no'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VCNVQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveBigIntegerField(default=0)),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
                ('question_data_type', models.CharField(choices=[('I', 'Image'), ('A', 'Audio'), ('V', 'Video'), ('T', 'Text')], default='Text', max_length=10)),
                ('question_value', models.PositiveIntegerField(default=10)),
                ('resources', models.JSONField(default={'Audio': {}, 'Image': {}, 'Video': {}})),
                ('picture_opened', models.BooleanField(default=False)),
                ('question_shown', models.BooleanField(default=False)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.exam')),
                ('target_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcnv_target_player', to='olympia.player')),
            ],
            options={
                'get_latest_by': ['exam', 'no'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VCNVRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.PositiveIntegerField(default=0)),
                ('question_data_type', models.CharField(default='Text', max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_value', models.PositiveIntegerField(default=10)),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('question_resources', models.JSONField(default={'Audio': {}, 'Image': {}, 'Video': {}})),
                ('player_answer', models.TextField()),
                ('question_type', models.CharField(choices=[('hn', 'HN'), ('cnv', 'CNV')], max_length=10)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('player_steal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcnv_steal_record', to='olympia.player')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.vcnvquestion')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.examrecord')),
            ],
            options={
                'get_latest_by': ['exam', 'record', 'question', 'question_no'],
                'abstract': False,
            },
        ),
    ]
