# Generated by Django 5.2.2 on 2025-06-14 13:38

import olympia.models.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0002_vcnvcontrol_kdcontrol_kdquestion_kdrecord_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdquestion',
            name='resources',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='kdrecord',
            name='question_resources',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vcnvquestion',
            name='resources',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vcnvrecord',
            name='question_resources',
            field=models.JSONField(default=dict),
        ),
    ]
