# Generated by Django 5.2.2 on 2025-06-14 14:29

import django.db.models.deletion
import olympia.models.base_models
import olympia.models.tt_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0003_alter_kdquestion_resources_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TTControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_question', models.BooleanField(default=False)),
                ('show_result', models.BooleanField(default=False)),
                ('duration', models.DurationField()),
            ],
        ),
        migrations.RemoveField(
            model_name='player',
            name='no',
        ),
        migrations.CreateModel(
            name='PlayerRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(default='', max_length=255)),
                ('score', models.PositiveIntegerField(default=0)),
                ('auth_id', models.CharField(default='', max_length=10)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.examrecord')),
            ],
        ),
        migrations.AlterField(
            model_name='kdcontrol',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kd_current_player', to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='kdcontrol',
            name='player_steal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kd_player_steal', to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='kdquestion',
            name='target_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kd_target_player', to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='kdrecord',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kd_player_record', to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='kdrecord',
            name='player_steal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='kd_steal_record', to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='vcnvquestion',
            name='target_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcnv_target_player', to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='vcnvrecord',
            name='player_steal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcnv_steal_record', to='olympia.playerrecord'),
        ),
        migrations.CreateModel(
            name='TTQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveBigIntegerField(default=0)),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
                ('question_data_type', models.CharField(choices=[('I', 'Image'), ('A', 'Audio'), ('V', 'Video'), ('T', 'Text')], default='Text', max_length=10)),
                ('question_value', models.PositiveIntegerField(default=10)),
                ('resources', models.JSONField(default=dict)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.exam')),
            ],
            options={
                'get_latest_by': ['exam', 'no'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TTRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.PositiveIntegerField(default=0)),
                ('question_data_type', models.CharField(default='Text', max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_value', models.PositiveIntegerField(default=10)),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('question_resources', models.JSONField(default=dict)),
                ('player_answer', models.JSONField(default=dict)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.ttquestion')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.examrecord')),
            ],
            options={
                'get_latest_by': ['exam', 'record', 'question', 'question_no'],
                'abstract': False,
            },
        ),
    ]
