# Generated by Django 5.2.2 on 2025-06-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0004_ttcontrol_remove_player_no_playerrecord_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ttcontrol',
            old_name='duration',
            new_name='answered_at',
        ),
    ]
