# Generated by Django 5.2.2 on 2025-06-14 15:55

import django.db.models.deletion
import olympia.models.base_models
import olympia.models.vcnv_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0005_rename_duration_ttcontrol_answered_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ttrecord',
            old_name='player_answer',
            new_name='player_answers',
        ),
        migrations.RemoveField(
            model_name='examrecord',
            name='players',
        ),
        migrations.RemoveField(
            model_name='examrecord',
            name='total_score',
        ),
        migrations.RemoveField(
            model_name='vcnvquestion',
            name='target_player',
        ),
        migrations.RemoveField(
            model_name='vcnvrecord',
            name='answered_at',
        ),
        migrations.RemoveField(
            model_name='vcnvrecord',
            name='player_steal',
        ),
        migrations.AddField(
            model_name='examrecord',
            name='current_record',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='vcnvquestion',
            name='question_type',
            field=models.CharField(choices=[('hn', 'HN'), ('cnv', 'CNV')], default='HN', max_length=10),
        ),
        migrations.AlterField(
            model_name='vcnvrecord',
            name='player_answer',
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='vcnvrecord',
            name='question_type',
            field=models.CharField(choices=[('hn', 'HN'), ('cnv', 'CNV')], default='HN', max_length=10),
        ),
        migrations.CreateModel(
            name='VDControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_picker', models.BooleanField(default=False)),
                ('picked_questions', models.CharField(default='0,0,0,0,0,0', max_length=6)),
                ('nshv_active', models.BooleanField(default=False)),
                ('nshv_turned_on', models.BooleanField(default=False)),
                ('show_question', models.BooleanField(default=False)),
                ('current_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olympia.playerrecord')),
            ],
        ),
        migrations.CreateModel(
            name='VDQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveBigIntegerField(default=0)),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
                ('question_data_type', models.CharField(choices=[('I', 'Image'), ('A', 'Audio'), ('V', 'Video'), ('T', 'Text')], default='Text', max_length=10)),
                ('question_value', models.PositiveIntegerField(default=10)),
                ('resources', models.JSONField(default=dict)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.exam')),
                ('target_player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vcnv_target_player', to='olympia.playerrecord')),
            ],
            options={
                'get_latest_by': ['exam', 'no'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VDRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.PositiveIntegerField(default=0)),
                ('question_data_type', models.CharField(default='Text', max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_value', models.PositiveIntegerField(default=10)),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('question_resources', models.JSONField(default=dict)),
                ('picked_question', models.CharField(default='0,0,0,0,0,0', max_length=6)),
                ('nshv', models.CharField(default='0,0,0', max_length=3)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vd_player_record', to='olympia.playerrecord')),
                ('player_steal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vd_steal_record', to='olympia.playerrecord')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.vdquestion')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.examrecord')),
            ],
            options={
                'get_latest_by': ['exam', 'record', 'question', 'question_no'],
                'abstract': False,
            },
        ),
    ]
