# Generated by Django 5.2.2 on 2025-06-14 16:36

import django.db.models.deletion
import olympia.models.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0007_remove_playerrecord_auth_id_playerrecord_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CHPControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('players_joined', models.CharField(default='0,0,0,0', max_length=4)),
                ('show_question', models.BooleanField(default=False)),
                ('player_steal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='olympia.playerrecord')),
            ],
        ),
        migrations.CreateModel(
            name='CHPQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.PositiveBigIntegerField(default=0)),
                ('question_text', models.TextField()),
                ('answer', models.TextField()),
                ('question_data_type', models.CharField(choices=[('I', 'Image'), ('A', 'Audio'), ('V', 'Video'), ('T', 'Text')], default='Text', max_length=10)),
                ('question_value', models.PositiveIntegerField(default=10)),
                ('resources', models.JSONField(default=dict)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.exam')),
            ],
            options={
                'get_latest_by': ['exam', 'no'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CHPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_no', models.PositiveIntegerField(default=0)),
                ('question_data_type', models.CharField(default='Text', max_length=10)),
                ('is_correct', models.BooleanField(default=False)),
                ('question_value', models.PositiveIntegerField(default=10)),
                ('question_text', models.TextField()),
                ('answer_text', models.TextField()),
                ('question_resources', models.JSONField(default=dict)),
                ('player_steal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.playerrecord')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.chpquestion')),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.examrecord')),
            ],
            options={
                'get_latest_by': ['exam', 'record', 'question', 'question_no'],
                'abstract': False,
            },
        ),
    ]
