# Generated by Django 5.2.2 on 2025-06-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0008_chpcontrol_chpquestion_chprecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ttrecord',
            name='player_answers',
            field=models.JSONField(),
        ),
    ]
