# Generated by Django 5.2.2 on 2025-06-14 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0009_alter_ttrecord_player_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vcnvrecord',
            name='player_answer',
            field=models.JSONField(),
        ),
    ]
