# Generated by Django 5.2.2 on 2025-06-15 06:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0011_alter_chprecord_player_steal'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('I', 'Image'), ('A', 'Audio'), ('V', 'Video'), ('T', 'Text')], default='Image', max_length=10)),
                ('resource', models.FileField(upload_to='resources/<django.db.models.fields.CharField>')),
            ],
        ),
        migrations.RemoveField(
            model_name='chprecord',
            name='question_resources',
        ),
        migrations.RemoveField(
            model_name='kdrecord',
            name='question_resources',
        ),
        migrations.RemoveField(
            model_name='ttrecord',
            name='question_resources',
        ),
        migrations.RemoveField(
            model_name='vcnvrecord',
            name='question_resources',
        ),
        migrations.RemoveField(
            model_name='vdrecord',
            name='question_resources',
        ),
        migrations.AlterField(
            model_name='chpcontrol',
            name='player_steal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='chprecord',
            name='player_steal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='chprecord',
            name='question_data_type',
            field=models.CharField(choices=[('I', 'Image'), ('A', 'Audio'), ('V', 'Video'), ('T', 'Text')], default='Text', max_length=10),
        ),
        migrations.AlterField(
            model_name='kdcontrol',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='kd_current_player', to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='kdcontrol',
            name='player_steal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='kd_player_steal', to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='kdquestion',
            name='target_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='kd_target_player', to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='kdrecord',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='kd_player_record', to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='kdrecord',
            name='player_steal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='kd_steal_record', to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='kdrecord',
            name='question_data_type',
            field=models.CharField(choices=[('I', 'Image'), ('A', 'Audio'), ('V', 'Video'), ('T', 'Text')], default='Text', max_length=10),
        ),
        migrations.AlterField(
            model_name='ttrecord',
            name='question_data_type',
            field=models.CharField(choices=[('I', 'Image'), ('A', 'Audio'), ('V', 'Video'), ('T', 'Text')], default='Text', max_length=10),
        ),
        migrations.AlterField(
            model_name='vcnvrecord',
            name='question_data_type',
            field=models.CharField(choices=[('I', 'Image'), ('A', 'Audio'), ('V', 'Video'), ('T', 'Text')], default='Text', max_length=10),
        ),
        migrations.AlterField(
            model_name='vdcontrol',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='vdquestion',
            name='target_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vcnv_target_player', to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='vdrecord',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vd_player_record', to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='vdrecord',
            name='player_steal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='vd_steal_record', to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='vdrecord',
            name='question_data_type',
            field=models.CharField(choices=[('I', 'Image'), ('A', 'Audio'), ('V', 'Video'), ('T', 'Text')], default='Text', max_length=10),
        ),
        migrations.AddField(
            model_name='chprecord',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympia.mediaresource'),
        ),
        migrations.AddField(
            model_name='kdrecord',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympia.mediaresource'),
        ),
        migrations.AddField(
            model_name='ttrecord',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympia.mediaresource'),
        ),
        migrations.AddField(
            model_name='vcnvrecord',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympia.mediaresource'),
        ),
        migrations.AddField(
            model_name='vdrecord',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympia.mediaresource'),
        ),
        migrations.AlterField(
            model_name='chpquestion',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympia.mediaresource'),
        ),
        migrations.AlterField(
            model_name='kdquestion',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympia.mediaresource'),
        ),
        migrations.AlterField(
            model_name='ttquestion',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympia.mediaresource'),
        ),
        migrations.AlterField(
            model_name='vcnvquestion',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympia.mediaresource'),
        ),
        migrations.AlterField(
            model_name='vdquestion',
            name='resources',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympia.mediaresource'),
        ),
    ]
