# Generated by Django 5.2.2 on 2025-06-15 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0012_mediaresource_remove_chprecord_question_resources_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaresource',
            options={'get_latest_by': 'media_type'},
        ),
        migrations.AddField(
            model_name='chpquestion',
            name='target_player',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='ttquestion',
            name='target_player',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='vcnvquestion',
            name='target_player',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='chpcontrol',
            name='player_steal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='olympia.player'),
        ),
        migrations.AlterField(
            model_name='kdcontrol',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='kd_current_player', to='olympia.player'),
        ),
        migrations.AlterField(
            model_name='kdcontrol',
            name='player_steal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='kd_player_steal', to='olympia.player'),
        ),
        migrations.AlterField(
            model_name='kdquestion',
            name='target_player',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vdcontrol',
            name='current_player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='olympia.player'),
        ),
        migrations.AlterField(
            model_name='vdquestion',
            name='target_player',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
