# Generated by Django 5.2.2 on 2025-06-15 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0013_alter_mediaresource_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaresource',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='olympia.exam'),
        ),
    ]
