# Generated by Django 5.2.2 on 2025-06-15 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('olympia', '0014_mediaresource_exam'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chpquestion',
            options={'get_latest_by': ['exam', 'question_no']},
        ),
        migrations.AlterModelOptions(
            name='kdquestion',
            options={'get_latest_by': ['exam', 'question_no']},
        ),
        migrations.AlterModelOptions(
            name='mediaresource',
            options={'get_latest_by': ['question', 'media_type']},
        ),
        migrations.AlterModelOptions(
            name='ttquestion',
            options={'get_latest_by': ['exam', 'question_no']},
        ),
        migrations.AlterModelOptions(
            name='vcnvquestion',
            options={'get_latest_by': ['exam', 'question_no']},
        ),
        migrations.AlterModelOptions(
            name='vdquestion',
            options={'get_latest_by': ['exam', 'question_no']},
        ),
        migrations.RenameField(
            model_name='chpquestion',
            old_name='no',
            new_name='question_no',
        ),
        migrations.RenameField(
            model_name='chpquestion',
            old_name='target_player',
            new_name='target_player_no',
        ),
        migrations.RenameField(
            model_name='kdquestion',
            old_name='no',
            new_name='question_no',
        ),
        migrations.RenameField(
            model_name='kdquestion',
            old_name='target_player',
            new_name='target_player_no',
        ),
        migrations.RenameField(
            model_name='ttquestion',
            old_name='no',
            new_name='question_no',
        ),
        migrations.RenameField(
            model_name='ttquestion',
            old_name='target_player',
            new_name='target_player_no',
        ),
        migrations.RenameField(
            model_name='vcnvquestion',
            old_name='no',
            new_name='question_no',
        ),
        migrations.RenameField(
            model_name='vcnvquestion',
            old_name='target_player',
            new_name='target_player_no',
        ),
        migrations.RenameField(
            model_name='vdquestion',
            old_name='no',
            new_name='question_no',
        ),
        migrations.RenameField(
            model_name='vdquestion',
            old_name='target_player',
            new_name='target_player_no',
        ),
        migrations.RemoveField(
            model_name='chpquestion',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='chprecord',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='kdquestion',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='kdrecord',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='mediaresource',
            name='exam',
        ),
        migrations.RemoveField(
            model_name='ttquestion',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='ttrecord',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='vcnvquestion',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='vcnvrecord',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='vdquestion',
            name='resources',
        ),
        migrations.RemoveField(
            model_name='vdrecord',
            name='resources',
        ),
        migrations.AddField(
            model_name='mediaresource',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mediaresource',
            name='object_id',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chprecord',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympia.chpquestion'),
        ),
        migrations.AlterField(
            model_name='kdrecord',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympia.kdquestion'),
        ),
        migrations.AlterField(
            model_name='ttrecord',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympia.ttquestion'),
        ),
        migrations.AlterField(
            model_name='vcnvrecord',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympia.vcnvquestion'),
        ),
        migrations.AlterField(
            model_name='vdrecord',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympia.vdquestion'),
        ),
    ]
