# Generated by Django 5.2.2 on 2025-06-16 08:39

import olympia.models.base_models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0015_alter_chpquestion_options_alter_kdquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaresource',
            name='resource',
            field=models.FileField(upload_to=olympia.models.base_models.MediaResource.get_upload_path),
        ),
    ]
