# Generated by Django 5.2.2 on 2025-06-16 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0016_alter_mediaresource_resource'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chpquestion',
            options={'get_latest_by': ['exam', '-question_no']},
        ),
        migrations.AlterModelOptions(
            name='kdquestion',
            options={'get_latest_by': ['exam', '-question_no']},
        ),
        migrations.AlterModelOptions(
            name='ttquestion',
            options={'get_latest_by': ['exam', '-question_no']},
        ),
        migrations.AlterModelOptions(
            name='vcnvquestion',
            options={'get_latest_by': ['exam', '-question_no']},
        ),
        migrations.AlterModelOptions(
            name='vdquestion',
            options={'get_latest_by': ['exam', '-question_no']},
        ),
        migrations.AlterField(
            model_name='chpquestion',
            name='question_data_type',
            field=models.CharField(choices=[('Image', 'I'), ('Audio', 'A'), ('Video', 'V'), ('Text', 'T')], default='Text', max_length=10),
        ),
        migrations.AlterField(
            model_name='chprecord',
            name='question_data_type',
            field=models.CharField(choices=[('Image', 'I'), ('Audio', 'A'), ('Video', 'V'), ('Text', 'T')], default='Text', max_length=10),
        ),
        migrations.AlterField(
            model_name='kdquestion',
            name='question_data_type',
            field=models.CharField(choices=[('Image', 'I'), ('Audio', 'A'), ('Video', 'V'), ('Text', 'T')], default='Text', max_length=10),
        ),
        migrations.AlterField(
            model_name='kdrecord',
            name='question_data_type',
            field=models.CharField(choices=[('Image', 'I'), ('Audio', 'A'), ('Video', 'V'), ('Text', 'T')], default='Text', max_length=10),
        ),
        migrations.AlterField(
            model_name='mediaresource',
            name='media_type',
            field=models.CharField(choices=[('Image', 'I'), ('Audio', 'A'), ('Video', 'V'), ('Text', 'T')], default='Image', max_length=10),
        ),
        migrations.AlterField(
            model_name='ttquestion',
            name='question_data_type',
            field=models.CharField(choices=[('Image', 'I'), ('Audio', 'A'), ('Video', 'V'), ('Text', 'T')], default='Text', max_length=10),
        ),
        migrations.AlterField(
            model_name='ttrecord',
            name='question_data_type',
            field=models.CharField(choices=[('Image', 'I'), ('Audio', 'A'), ('Video', 'V'), ('Text', 'T')], default='Text', max_length=10),
        ),
        migrations.AlterField(
            model_name='vcnvquestion',
            name='question_data_type',
            field=models.CharField(choices=[('Image', 'I'), ('Audio', 'A'), ('Video', 'V'), ('Text', 'T')], default='Text', max_length=10),
        ),
        migrations.AlterField(
            model_name='vcnvrecord',
            name='question_data_type',
            field=models.CharField(choices=[('Image', 'I'), ('Audio', 'A'), ('Video', 'V'), ('Text', 'T')], default='Text', max_length=10),
        ),
        migrations.AlterField(
            model_name='vdquestion',
            name='question_data_type',
            field=models.CharField(choices=[('Image', 'I'), ('Audio', 'A'), ('Video', 'V'), ('Text', 'T')], default='Text', max_length=10),
        ),
        migrations.AlterField(
            model_name='vdrecord',
            name='question_data_type',
            field=models.CharField(choices=[('Image', 'I'), ('Audio', 'A'), ('Video', 'V'), ('Text', 'T')], default='Text', max_length=10),
        ),
    ]
