# Generated by Django 5.2.2 on 2025-06-17 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0017_alter_chpquestion_options_alter_kdquestion_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chpquestion',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kdquestion',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ttquestion',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vcnvquestion',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vcnvquestion',
            name='question_type',
            field=models.CharField(choices=[('HN', 'HN'), ('TT', 'TT'), ('CNV', 'CNV')], default='HN', max_length=10),
        ),
        migrations.AlterField(
            model_name='vcnvrecord',
            name='question_type',
            field=models.CharField(choices=[('HN', 'HN'), ('TT', 'TT'), ('CNV', 'CNV')], default='HN', max_length=10),
        ),
        migrations.AlterField(
            model_name='vdquestion',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
