# Generated by Django 5.2.2 on 2025-06-17 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0018_alter_chpquestion_answer_alter_kdquestion_answer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chpquestion',
            options={'get_latest_by': ['exam', '-target_player_no', '-question_no']},
        ),
        migrations.AlterModelOptions(
            name='kdquestion',
            options={'get_latest_by': ['exam', '-target_player_no', '-question_no']},
        ),
        migrations.AlterModelOptions(
            name='ttquestion',
            options={'get_latest_by': ['exam', '-target_player_no', '-question_no']},
        ),
        migrations.AlterModelOptions(
            name='vcnvquestion',
            options={'get_latest_by': ['exam', '-target_player_no', '-question_no']},
        ),
        migrations.AlterModelOptions(
            name='vdquestion',
            options={'get_latest_by': ['exam', '-target_player_no', '-question_no']},
        ),
    ]
