# Generated by Django 5.2.2 on 2025-06-18 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('olympia', '0021_remove_chprecord_media_remove_kdrecord_media_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examrecord',
            name='exam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='olympia.exam'),
        ),
        migrations.AlterField(
            model_name='mediaresource',
            name='content_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
    ]
