# Generated by Django 5.2.2 on 2025-06-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0022_alter_examrecord_exam_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chprecord',
            name='answer_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kdrecord',
            name='answer_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ttrecord',
            name='answer_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vcnvrecord',
            name='answer_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vdrecord',
            name='answer_text',
            field=models.TextField(null=True),
        ),
    ]
