# Generated by Django 5.2.2 on 2025-06-19 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0023_alter_chprecord_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='examrecord',
            options={'get_latest_by': ['current_record', 'exam', 'played_at']},
        ),
    ]
