# Generated by Django 5.2.2 on 2025-06-19 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0024_alter_examrecord_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chprecord',
            name='question_data_type',
            field=models.CharField(choices=[('Image', 'I'), ('Audio', 'A'), ('Video', 'V'), ('Text', 'T')], default='Text', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='chprecord',
            name='question_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='kdrecord',
            name='question_data_type',
            field=models.CharField(choices=[('Image', 'I'), ('Audio', 'A'), ('Video', 'V'), ('Text', 'T')], default='Text', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='kdrecord',
            name='question_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='ttrecord',
            name='player_answers',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='ttrecord',
            name='question_data_type',
            field=models.CharField(choices=[('Image', 'I'), ('Audio', 'A'), ('Video', 'V'), ('Text', 'T')], default='Text', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='ttrecord',
            name='question_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vcnvrecord',
            name='player_answer',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='vcnvrecord',
            name='question_data_type',
            field=models.CharField(choices=[('Image', 'I'), ('Audio', 'A'), ('Video', 'V'), ('Text', 'T')], default='Text', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vcnvrecord',
            name='question_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='vcnvrecord',
            name='question_type',
            field=models.CharField(choices=[('HN', 'HN'), ('TT', 'TT'), ('CNV', 'CNV')], default='HN', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vdrecord',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vd_player_record', to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='vdrecord',
            name='player_steal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vd_steal_record', to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='vdrecord',
            name='question_data_type',
            field=models.CharField(choices=[('Image', 'I'), ('Audio', 'A'), ('Video', 'V'), ('Text', 'T')], default='Text', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='vdrecord',
            name='question_text',
            field=models.TextField(null=True),
        ),
    ]
