# Generated by Django 5.2.2 on 2025-06-24 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0025_alter_chprecord_question_data_type_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chpquestion',
            old_name='answer',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='kdquestion',
            old_name='answer',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='ttquestion',
            old_name='answer',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='vcnvquestion',
            old_name='answer',
            new_name='answer_text',
        ),
        migrations.RenameField(
            model_name='vdquestion',
            old_name='answer',
            new_name='answer_text',
        ),
    ]
