# Generated by Django 5.2.2 on 2025-06-24 08:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0026_rename_answer_chpquestion_answer_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kdrecord',
            name='player',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='kd_player_record', to='olympia.playerrecord'),
        ),
        migrations.AlterField(
            model_name='vdrecord',
            name='player_steal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='vd_steal_record', to='olympia.playerrecord'),
        ),
    ]
