# Generated by Django 5.2.2 on 2025-06-24 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0027_alter_kdrecord_player_alter_vdrecord_player_steal'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='playerrecord',
            options={'get_latest_by': ['record', 'no']},
        ),
    ]
