# Generated by Django 5.2.2 on 2025-06-24 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0028_alter_playerrecord_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chprecord',
            options={'get_latest_by': ['record', 'question', '-question_no']},
        ),
        migrations.AlterModelOptions(
            name='kdrecord',
            options={'get_latest_by': ['record', 'question', '-question_no']},
        ),
        migrations.AlterModelOptions(
            name='ttrecord',
            options={'get_latest_by': ['record', 'question', '-question_no']},
        ),
        migrations.AlterModelOptions(
            name='vcnvrecord',
            options={'get_latest_by': ['record', 'question', '-question_no']},
        ),
        migrations.AlterModelOptions(
            name='vdrecord',
            options={'get_latest_by': ['record', 'question', '-question_no']},
        ),
    ]
