# Generated by Django 5.2.2 on 2025-06-24 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('olympia', '0029_alter_chprecord_options_alter_kdrecord_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ttcontrol',
            name='answered_at',
        ),
    ]
